name: progen3d-snap
version: "0.74-svn"
summary: Grammar based 3d Procedural Generator
description: 
  ProGen3d is a grammar based procedural generator with textures and can export to PLY format.
confinement: strict
base: core20
parts:
  progen3d-snap:
    plugin: make
    source-type: git
    source: https://github.com/pghauff55/ProGen3d.git
    build-packages:
      - g++
      - make
      - build-essential
      - libgtk-3-dev
      - libgtk-3-0
      - libgl1-mesa-glx
      - libglu1-mesa-dev
      - libepoxy-dev
    
apps:
  progen3d-snap:
    command: ProGen3d
  
